version: '3.7'

services:
  web:
    image: api
    build: .
    command: go run main.go
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis