version: '3.7'

services:
  web:
    image: api
    build: .
    command: go run main.go
    environment:
      - ADDR=redis:6379
      - PASSWORD=
      - DB=0
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"